---
version: '3.8'

secrets:
  openssh_secret__user_password:
    file: ./sshd/secrets/user_password.txt

networks:
  jumphost-net:
    name: jumphost_net
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: "10.22.0.0/16"

services:
  openssh:
    image: ghcr.io/linuxserver/openssh-server:version-8.3_p1-r0
    hostname: jumphost-openssh
    ports:
      - target: 2222
        published: 32222
    networks:
      - jumphost-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2222"]
      interval: 10s
      timeout: 5s
    env_file:
      - openssh.env
    volumes:
      - ./sshd/data:/config
    secrets:
      - source: openssh_secret__user_password
        target: secret__user_password
        uid: '0'
        gid: '0'
        mode: 0400
    deploy:
      placement:
        constraints:
          - node.labels.openssh == true
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        order: start-first